#! /bin/sh
# refer https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/ to use natural scrolling and tap to enter

pgrep -x sxhkd > /dev/null || sxhkd &
cd ~/.config/polybar/ && ./bspwmpolybar.sh &

picom &

feh --bg-fill ~/backgrounds/nice-blue-background.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color   "#b16286"
bspc config active_border_color   "#d65d0e"
bspc config focused_border_color  "#98971a"
bspc config presel-feedback_color "#d65d0e"

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
